### ISSUE TITLE
Unable to edit polls

### ISSUE THREAD

**Issue by WPprodigy** [Automattic/crowdsignal-plugin#19]
The following check is failing on a site, causing all polls to be un-editable. It also results in a false-positive message about not being able to create a new poll when opening up the page to create a new poll: 

https://github.com/Automattic/polldaddy-plugin/blob/master/polldaddy.php#L5233-L5240

The `$poll->_owner` seems to always be equal to `1`. So if there isn't a user on the site with this ID, then `can_edit` will always fail.

A: I'm not really sure how the _owner value is being set, as I'm not seeing anything client-side where this happened.
B: I'm not so sure this check is even necessary, especially on a non-multisite.

CC @donnchawp 

86965-vip-zd

**Comment by rebeccahum** [comment]
Running into this as well in #96420-z which is using a multisite instance.

**Comment by donnchawp** [comment]
I think we need to drastically simplify `can_edit` so that we only check if the current user is an author or better on the blog.
