### ISSUE TITLE
Update plugin's imagery and branding

### ISSUE THREAD

**Issue by CGastrell** [Automattic/crowdsignal-plugin#23]
Current .org plugin page holds outdated images and icons since the rename/rebranding:

![image](https://user-images.githubusercontent.com/157240/53654677-0c5b0f80-3c2d-11e9-8fc9-79dd6972a455.png)

Plugin page: https://wordpress.org/plugins/polldaddy
Trello card: https://trello.com/c/2YFM07xU/15-update-design-for-plugin-store-page
Ref: https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/

@digitalwaveride Mentioning to keep track of this

Preview can be attained by appending `?banner_url=A_URL_TO_YOUR_IMAGE`

**Comment by roundhill** [comment]
@CGastrell we can close this one, I think?

**Comment by CGastrell** [comment]
Indeed, thanks!
