### ISSUE TITLE
Unable to store Multiple Choice as default poll settings

### ISSUE THREAD

**Issue by jom** [Automattic/crowdsignal-plugin#32]
In testing #31, I found an issue where I wasn't able to save this setting.

<img width="815" alt="Screen Shot 2019-12-19 at 3 21 13 PM" src="https://user-images.githubusercontent.com/68693/71217647-52906680-2273-11ea-92dd-e4745031a2b9.png">

**Comment by annacmc** [comment]
Have encountered another report of this in wpcom 2672298-zen and have replicated on a testing site in Calypso https://d.pr/i/zKJ6BH

**Comment by jom** [comment]
Closed by #34 

@annacmc The #34 PR fixes both, but I'm not sure when it will land in WPCOM.
