### ISSUE TITLE
Function get_magic_quotes_gpc() is deprecated since PHP 7.4

### ISSUE THREAD

**Issue by mslinnea** [Automattic/crowdsignal-plugin#45]
```
FILE: /crowdsignal-plugin/polldaddy-client.php
------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
------------------------------------------------------------------------------
 1337 | WARNING | Function get_magic_quotes_gpc() is deprecated since PHP 7.4
------------------------------------------------------------------------------
```

#### Steps to Reproduce
1. Run phpcs to check for compatibility issues as described at https://github.com/PHPCompatibility/PHPCompatibilityWP

#### What I Expected
No PHP warnings for 7.4.

#### Context / Source
WordPress requires a PHP minimum version of 5.6.2.
get_magic_quotes_gpc() will always return false since version 5.4.0.

Therefore, I think this function can be removed.

**Comment by donnchawp** [comment]
Thanks. I just merged #40 which removed this function call.
