### ISSUE TITLE
Text encoding issue with Rating Widget Results in WordPress Admin 

### ISSUE THREAD

**Issue by gaurav1984** [Automattic/crowdsignal-plugin#83]
#### Steps to Reproduce
1. Go to WordPress Admin > Feedback > Ratings
2. Filter the results to Daily, Weekly or Monthly views
3. The spaces in the title is replaced with `20` and an exclamation point replaced with `21` in the title of the rating

#### Screenshot / Video
![Annotation on 2022-03-29 at 13-13-34](https://user-images.githubusercontent.com/2140288/160559964-b9e5d06b-641b-4999-8d6c-297582bc1025.png)

#### Context / Source

Reported in https://wordpress.org/support/topic/ratings-widget-afu/

**Comment by CGastrell** [comment]
A fix was deployed for this on D74537-code
Ratings will continue to fix themselves as they are voted upon
